version: '3.8'

services:
  cocreate:
    image: sb-cocreate
    #build: .
    ports:
      - 8080:8080


  mysqldb:
   container_name: mysql-db
   image: mysql:latest
   restart: unless-stopped
   ports:
     - "3366:3306"
   environment:
      MYSQL_ROOT_PASSWORD: root
      #MYSQL_USER: root
      MYSQL_DATABASE: cocreate


